FROM node:14.9

#set working directory
RUN mkdir /app

#install app dependencies
COPY package.json package-lock.json* ./

RUN npm install

#add app
COPY . .

#expose app on port
EXPOSE 3000

#start app
CMD ["npm", "start"]